name: CI/CD Pipeline

on:
  push:
    branches:
      - dev  # Runs on every push to dev
  pull_request:
    branches:
      - main  # Runs on PRs to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Deploy (Mock Step)
        run: echo "Deploying to AWS..."
